Add popup menu
Grandi0z/Portfolio-joskal pull request #11
Opened 2022-12-21 22:11 UTC by Grandi0z

### In this milestone we :
> add a responsive popup menu in the section ''recent works''
>The popup display different information relative to the project the user chooses

2022-12-21 22:22 UTC, huseyinbiyik commented
Hi @Grandi0z,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![Alt Text](https://media.giphy.com/media/xUPGcwE3CUkXlvonug/giphy.gif)

## Invalid Code Review Request

❌You have submitted a project, that has no contribution from the pair programming partner. Kindly check the [Work and Submission Mode](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/8_popup.md#work-and-submission-mode) ❌

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-22 16:35 UTC, OyePriscilla requested changes
Hi @Grandi0z 😃, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425615-8927e377-c543-407b-8da4-5c09fecc261b.gif)

## Highlights
Github flow observed✔️
Linters checks passed ✔️ 

## Required Changes ♻️
__ kindly check the inline comments below__

## Optional suggestions
[optional] Please kindly increase the size of your `nav items   id="deskNav"`for the desktop version.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-22 16:35 UTC, OyePriscilla commented on style/styles.css
> +  }
- [ ] Please kindly add margin to your popup window for both desktop and mobile version. Part of our duty as developers is our capability to reproduce any design given to us expected. 👍 

## Figma design for desktop version

![q2](https://user-images.githubusercontent.com/103386183/209178472-b82299a7-fd6a-41b8-8546-d75dccd07dc7.png)

## Figma design for mobile version
![q3](https://user-images.githubusercontent.com/103386183/209178548-c8c1f273-9285-4eff-af4b-3847e8d38b4f.png)

2022-12-22 18:53 UTC, Gopxfs approved these changes
# 🟢 STATUS: APPROVED 🟢

## Hello @Grandi0z 👋,

Your project is complete! You followed all the requirements, feel free to merge it! 😄
Congratulations! 🎉 

<img src="https://media.giphy.com/media/cXblnKXr2BQOaYnTni/giphy.gif">

## Highlights
✔️ Linters are passing successfully.
✔️ Implemented all the changes requested by the previous reviewer. Well done!

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-22 19:21 UTC, merged