Build the body and the footer
Grandi0z/Portfolio-joskal pull request #3
Opened 2022-12-03 22:59 UTC by Grandi0z

#### In this code we :

- Give a column structure to the project with Grid and Flexbox
- Add background
- stylize the text content

2022-12-03 23:15 UTC, emmiiorji requested changes
Hi @Grandi0z, 
# Status: Changes Required ♻️

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![A little bit more](https://user-images.githubusercontent.com/20554583/205466103-3d66b732-4ee8-4856-8526-32db7c74671b.gif)


## Good Highlights✔️

- Linter checks are passing
- Good commit messages
- Adherence to GitHub flow
- Good design


## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 23:15 UTC, emmiiorji commented on index.html
> +                    </div>
You have a beautiful design. However, you'll agree that the list of project technologies is just that - a list. I think that using an `li` tag for each item and a `ul` tag to enclose them all will be more semantic.

Remember to modify it in all the projects.

2022-12-03 23:15 UTC, emmiiorji commented on style/styles.css
> +}
As mentioned in the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/100a933087f033def9233c8cce29c72194391fe0/portfolio/2_mobile.md?plain=1#L51), kindly use a `display: grid` property for the container of the works section.

2022-12-04 00:45 UTC, Owusu-Desmond approved these changes
Hi @Grandi0z 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/keIhXfvZjgsj2BZMg9/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the setup of the project ✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-04 00:51 UTC, merged